# Generated by Django 3.1.8 on 2021-05-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=500, unique=True)),
                ('description', models.CharField(default='Official Music', max_length=500)),
                ('published_at', models.DateTimeField()),
                ('thumbnail', models.URLField(default='https://upload.wikimedia.org/wikipedia/commons/3/35/Simple_Music.svg')),
            ],
            options={
                'db_table': 'videos',
            },
        ),
    ]
