# Generated by Django 3.1.8 on 2021-05-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('video_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(default='Official Music', max_length=100)),
                ('published_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'videos',
            },
        ),
    ]
