# Generated by Django 3.1.8 on 2021-05-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetch_music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='thumbnail',
            field=models.URLField(default='https://upload.wikimedia.org/wikipedia/commons/3/35/Simple_Music.svg'),
        ),
    ]
