# Generated by Django 3.1.8 on 2021-05-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetch_music', '0002_auto_20210524_0929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos',
            name='id',
        ),
        migrations.AlterField(
            model_name='videos',
            name='title',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='videos',
            name='video_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
