# Generated by Django 3.1.8 on 2021-05-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetch_music', '0003_auto_20210524_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
